// Regenerates the bundled benchmark data files for sidestep.html.
// Run from the repo root: node scripts/update_market_data.mjs
// Invoked nightly by .github/workflows/update-market-data.yml.
import { writeFileSync } from 'fs';

async function fetchText(url, headers = {}) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
  return res.text();
}

// S&P 500 — FRED series SP500 (trailing 10y of daily closes)
const fredCsv = await fetchText('https://fred.stlouisfed.org/graph/fredgraph.csv?id=SP500');
const spRows = fredCsv.trim().split('\n').slice(1)
  .map(l => l.split(','))
  .filter(([d, c]) => /^\d{4}-\d{2}-\d{2}$/.test(d) && c && c !== '.' && !isNaN(parseFloat(c)))
  .map(([d, c]) => [d, parseFloat(c)]);
if (spRows.length < 1000) throw new Error(`FRED returned only ${spRows.length} rows`);
writeFileSync('assets/sp500_data.js',
  '// S&P 500 daily closes (source: FRED series SP500, https://fred.stlouisfed.org/series/SP500)\n'
  + '// Regenerated by scripts/update_market_data.mjs — do not edit by hand.\n'
  + 'window.SP500_DATA = ' + JSON.stringify(spRows) + ';\n');
console.log(`SP500: ${spRows.length} rows through ${spRows[spRows.length - 1][0]}`);

// VIGAX — Yahoo Finance chart API (needs a browser User-Agent)
const yahoo = JSON.parse(await fetchText(
  'https://query1.finance.yahoo.com/v8/finance/chart/VIGAX?range=10y&interval=1d',
  { 'User-Agent': 'Mozilla/5.0' }));
const result = yahoo.chart.result[0];
const closes = result.indicators.quote[0].close;
const vgRows = [];
for (let i = 0; i < result.timestamp.length; i++) {
  if (closes[i] == null) continue;
  vgRows.push([new Date(result.timestamp[i] * 1000).toISOString().slice(0, 10),
               Math.round(closes[i] * 100) / 100]);
}
if (vgRows.length < 1000) throw new Error(`Yahoo returned only ${vgRows.length} rows`);
writeFileSync('assets/vigax_data.js',
  '// VIGAX (Vanguard Growth Index Admiral) daily NAV closes (source: Yahoo Finance chart API)\n'
  + '// Regenerated by scripts/update_market_data.mjs — do not edit by hand.\n'
  + 'window.VIGAX_DATA = ' + JSON.stringify(vgRows) + ';\n');
console.log(`VIGAX: ${vgRows.length} rows through ${vgRows[vgRows.length - 1][0]}`);
